dipper: configs: vintf: Remove android.hardware.gnss hal
error: Cannot add manifest fragmen
t /vendor/etc/vintf/manifest/android.hardware.gnss@2.1-service-qti.xml: HAL "and
roid.hardware.gnss" has a conflict: Conflicting FqInstance: @2.0::IGnss/default
(from /vendor/etc/vintf/manifest.xml) vs. @2.1::IGnss/default (from /vendor/etc/
vintf/manifest/android.hardware.gnss@2.1-service-qti.xml). Check whether or not
multiple modules providing the same HAL are installed.

Multiple conflicts in: https://github.com/AOSPA/android_hardware_qcom_gps/blob/uvite-legacy-component/android/2.1/android.hardware.gnss%402.1-service-qti.xml

Signed-off-by: xiaoleGun <1592501605@qq.com>